stages:
  - build
  - test
  - deploy
image: docker
services:
  - docker:dind
builder:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ksenianikolaeva/devops-netology:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker push ksenianikolaeva/devops-netology:gitlab-$CI_COMMIT_SHORT_SHA
  except:
    - main
deployer:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ksenianikolaeva/devops-netology:latest .
    - docker push ksenianikolaeva/devops-netology:latest
  only:
    - main